name: Publish to PyPI
on:
  push
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: testpypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          python -m build

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
